### ISSUE TITLE
Not to override ember-snippets

### ISSUE THREAD

**Issue by Exelord** [jbailey4/atom-ember-module-snippets#1]
Hey,
is there any option to not override snippets from https://github.com/mattmcmanus/atom-ember-snippets ?

**Comment by jbailey4** [comment]
@Exelord It seems Atom snippets are auto-imported, so basically the last snippet to be imported wins. I researched this issue and can't seem to find a nice way to prevent this with Atom snippets.

I'm thinking what I will have to do, is create a common namespace for each `prefix`, something like:

`'prefix': 'Emcomponent'`

**Comment by Exelord** [comment]
what about `im` prefix?
Like: `imcomponent` - `import Component` etc...

**Comment by jbailey4** [comment]
@Exelord 👍  sounds good, makes sense to me.

I'll try to get this out asap.

**Comment by jbailey4** [comment]
@Exelord updating to `v1.0.0` should fix this issue. 
Closing for now, feel free to reopen if you still have the same issue after updating.

**Comment by Exelord** [comment]
Awesome! works as hell! :D Thank you
