### ISSUE TITLE
Merge project with atom-ember-snippets?

### ISSUE THREAD

**Issue by mattmcmanus** [jbailey4/atom-ember-module-snippets#3]
I was planning on adding the imports to atom-ember-snippets (re https://github.com/mattmcmanus/atom-ember-snippets/issues/24) and was made aware of this package. Would you be interested in merging projects? I'd definitely don't want to duplicate efforts and it seems like we're already stepping on each other's toes. I'd happily add you as a contributor to the repo

**Comment by jbailey4** [comment]
@mattmcmanus Sure no problem. I did come across atom-ember-snippets before creating this package, but didn't see any support for imports. I should've looked at the issues 😊 

> I'd happily add you as a contributor to the repo

Sounds good, thanks. I'll PR these snippets asap.

**Comment by mattmcmanus** [comment]
No worries at all. Who has time to go through all of the issues? Thanks for being flexible. I'll add you as a contributor on the project

**Comment by jbailey4** [comment]
@mattmcmanus Closing, as the projects are merged now
