### ISSUE TITLE
Allow user to import ember-decorators modules

### ISSUE THREAD

**Issue by axyxnz** [jbailey4/atom-ember-module-snippets#6]
I am not sure whether this is a good idea or not since decorators feature is not merged in Ember yet.

But it would be great if this plugin can support modules for `ember-decorators` (https://github.com/ember-decorators/ember-decorators) for people who is trying out latest features of Ember.

Prefix | Module
------ | -------
imdecoComponent | @ember-decorators/component
imdecoController | @ember-decorators/controller
imdecoData | @ember-decorators/data
imdecoObject | @ember-decorators/object
imdecoService | @ember-decorators/service

i.e.
```
  'Ember.Component':
    'prefix': 'imdecoComponent'
    'leftLabelHTML': '<span style="color:#E46651">Ember Decorators module</span>'
    'body': 'import Component from \'@ember-decorators/component\';'
```

@jbailey4 What do you think?

**Comment by jbailey4** [comment]
@axyxnz I think that would be a good idea, considering how popular `ember-decorators` is, however, this project has been ported to the [ember-snippets](https://github.com/mattmcmanus/atom-ember-snippets) repo and potential features would make more sense their instead.

Perhaps we can port this issue over there to discuss.

**Comment by axyxnz** [comment]
I realized after creating an issue that this project has been deprecated. It's a good idea to discuss there.
